// Auto-generated ISO 3166-1 country list with dial codes — run: node scripts/gen-countries.js
export interface CountryEntry {
  code: string;   // ISO 3166-1 alpha-2
  dial: string;   // e.g. "+1"
  name: string;
  flag: string;   // emoji flag
}

function flag(cca2: string): string {
  return cca2
    .toUpperCase()
    .split('')
    .map(c => String.fromCodePoint(0x1f1e6 - 65 + c.charCodeAt(0)))
    .join('');
}

export const COUNTRIES: CountryEntry[] = [
  {code:'AF',dial:'+93',name:'Afghanistan',flag:flag('AF')},
  {code:'AX',dial:'+358',name:'Åland Islands',flag:flag('AX')},
  {code:'AL',dial:'+355',name:'Albania',flag:flag('AL')},
  {code:'DZ',dial:'+213',name:'Algeria',flag:flag('DZ')},
  {code:'AS',dial:'+1684',name:'American Samoa',flag:flag('AS')},
  {code:'AD',dial:'+376',name:'Andorra',flag:flag('AD')},
  {code:'AO',dial:'+244',name:'Angola',flag:flag('AO')},
  {code:'AI',dial:'+1264',name:'Anguilla',flag:flag('AI')},
  {code:'AQ',dial:'+672',name:'Antarctica',flag:flag('AQ')},
  {code:'AG',dial:'+1268',name:'Antigua and Barbuda',flag:flag('AG')},
  {code:'AR',dial:'+54',name:'Argentina',flag:flag('AR')},
  {code:'AM',dial:'+374',name:'Armenia',flag:flag('AM')},
  {code:'AW',dial:'+297',name:'Aruba',flag:flag('AW')},
  {code:'AU',dial:'+61',name:'Australia',flag:flag('AU')},
  {code:'AT',dial:'+43',name:'Austria',flag:flag('AT')},
  {code:'AZ',dial:'+994',name:'Azerbaijan',flag:flag('AZ')},
  {code:'BS',dial:'+1242',name:'Bahamas',flag:flag('BS')},
  {code:'BH',dial:'+973',name:'Bahrain',flag:flag('BH')},
  {code:'BD',dial:'+880',name:'Bangladesh',flag:flag('BD')},
  {code:'BB',dial:'+1246',name:'Barbados',flag:flag('BB')},
  {code:'BY',dial:'+375',name:'Belarus',flag:flag('BY')},
  {code:'BE',dial:'+32',name:'Belgium',flag:flag('BE')},
  {code:'BZ',dial:'+501',name:'Belize',flag:flag('BZ')},
  {code:'BJ',dial:'+229',name:'Benin',flag:flag('BJ')},
  {code:'BM',dial:'+1441',name:'Bermuda',flag:flag('BM')},
  {code:'BT',dial:'+975',name:'Bhutan',flag:flag('BT')},
  {code:'BO',dial:'+591',name:'Bolivia',flag:flag('BO')},
  {code:'BA',dial:'+387',name:'Bosnia and Herzegovina',flag:flag('BA')},
  {code:'BW',dial:'+267',name:'Botswana',flag:flag('BW')},
  {code:'BV',dial:'+47',name:'Bouvet Island',flag:flag('BV')},
  {code:'BR',dial:'+55',name:'Brazil',flag:flag('BR')},
  {code:'IO',dial:'+246',name:'British Indian Ocean Territory',flag:flag('IO')},
  {code:'VG',dial:'+1284',name:'British Virgin Islands',flag:flag('VG')},
  {code:'BN',dial:'+673',name:'Brunei',flag:flag('BN')},
  {code:'BG',dial:'+359',name:'Bulgaria',flag:flag('BG')},
  {code:'BF',dial:'+226',name:'Burkina Faso',flag:flag('BF')},
  {code:'BI',dial:'+257',name:'Burundi',flag:flag('BI')},
  {code:'KH',dial:'+855',name:'Cambodia',flag:flag('KH')},
  {code:'CM',dial:'+237',name:'Cameroon',flag:flag('CM')},
  {code:'CA',dial:'+1',name:'Canada',flag:flag('CA')},
  {code:'CV',dial:'+238',name:'Cape Verde',flag:flag('CV')},
  {code:'BQ',dial:'+599',name:'Caribbean Netherlands',flag:flag('BQ')},
  {code:'KY',dial:'+1345',name:'Cayman Islands',flag:flag('KY')},
  {code:'CF',dial:'+236',name:'Central African Republic',flag:flag('CF')},
  {code:'TD',dial:'+235',name:'Chad',flag:flag('TD')},
  {code:'CL',dial:'+56',name:'Chile',flag:flag('CL')},
  {code:'CN',dial:'+86',name:'China',flag:flag('CN')},
  {code:'CX',dial:'+61',name:'Christmas Island',flag:flag('CX')},
  {code:'CC',dial:'+61',name:'Cocos (Keeling) Islands',flag:flag('CC')},
  {code:'CO',dial:'+57',name:'Colombia',flag:flag('CO')},
  {code:'KM',dial:'+269',name:'Comoros',flag:flag('KM')},
  {code:'CG',dial:'+242',name:'Congo',flag:flag('CG')},
  {code:'CK',dial:'+682',name:'Cook Islands',flag:flag('CK')},
  {code:'CR',dial:'+506',name:'Costa Rica',flag:flag('CR')},
  {code:'CI',dial:'+225',name:'Côte d\'Ivoire',flag:flag('CI')},
  {code:'HR',dial:'+385',name:'Croatia',flag:flag('HR')},
  {code:'CU',dial:'+53',name:'Cuba',flag:flag('CU')},
  {code:'CW',dial:'+599',name:'Curaçao',flag:flag('CW')},
  {code:'CY',dial:'+357',name:'Cyprus',flag:flag('CY')},
  {code:'CZ',dial:'+420',name:'Czechia',flag:flag('CZ')},
  {code:'DK',dial:'+45',name:'Denmark',flag:flag('DK')},
  {code:'DJ',dial:'+253',name:'Djibouti',flag:flag('DJ')},
  {code:'DM',dial:'+1767',name:'Dominica',flag:flag('DM')},
  {code:'DO',dial:'+1',name:'Dominican Republic',flag:flag('DO')},
  {code:'CD',dial:'+243',name:'DR Congo',flag:flag('CD')},
  {code:'EC',dial:'+593',name:'Ecuador',flag:flag('EC')},
  {code:'EG',dial:'+20',name:'Egypt',flag:flag('EG')},
  {code:'SV',dial:'+503',name:'El Salvador',flag:flag('SV')},
  {code:'GQ',dial:'+240',name:'Equatorial Guinea',flag:flag('GQ')},
  {code:'ER',dial:'+291',name:'Eritrea',flag:flag('ER')},
  {code:'EE',dial:'+372',name:'Estonia',flag:flag('EE')},
  {code:'SZ',dial:'+268',name:'Eswatini',flag:flag('SZ')},
  {code:'ET',dial:'+251',name:'Ethiopia',flag:flag('ET')},
  {code:'FK',dial:'+500',name:'Falkland Islands',flag:flag('FK')},
  {code:'FO',dial:'+298',name:'Faroe Islands',flag:flag('FO')},
  {code:'FJ',dial:'+679',name:'Fiji',flag:flag('FJ')},
  {code:'FI',dial:'+358',name:'Finland',flag:flag('FI')},
  {code:'FR',dial:'+33',name:'France',flag:flag('FR')},
  {code:'GF',dial:'+594',name:'French Guiana',flag:flag('GF')},
  {code:'PF',dial:'+689',name:'French Polynesia',flag:flag('PF')},
  {code:'TF',dial:'+262',name:'French Southern and Antarctic Lands',flag:flag('TF')},
  {code:'GA',dial:'+241',name:'Gabon',flag:flag('GA')},
  {code:'GM',dial:'+220',name:'Gambia',flag:flag('GM')},
  {code:'GE',dial:'+995',name:'Georgia',flag:flag('GE')},
  {code:'DE',dial:'+49',name:'Germany',flag:flag('DE')},
  {code:'GH',dial:'+233',name:'Ghana',flag:flag('GH')},
  {code:'GI',dial:'+350',name:'Gibraltar',flag:flag('GI')},
  {code:'GR',dial:'+30',name:'Greece',flag:flag('GR')},
  {code:'GL',dial:'+299',name:'Greenland',flag:flag('GL')},
  {code:'GD',dial:'+1473',name:'Grenada',flag:flag('GD')},
  {code:'GP',dial:'+590',name:'Guadeloupe',flag:flag('GP')},
  {code:'GU',dial:'+1671',name:'Guam',flag:flag('GU')},
  {code:'GT',dial:'+502',name:'Guatemala',flag:flag('GT')},
  {code:'GG',dial:'+44',name:'Guernsey',flag:flag('GG')},
  {code:'GN',dial:'+224',name:'Guinea',flag:flag('GN')},
  {code:'GW',dial:'+245',name:'Guinea-Bissau',flag:flag('GW')},
  {code:'GY',dial:'+592',name:'Guyana',flag:flag('GY')},
  {code:'HT',dial:'+509',name:'Haiti',flag:flag('HT')},
  {code:'HM',dial:'+672',name:'Heard Island and McDonald Islands',flag:flag('HM')},
  {code:'HN',dial:'+504',name:'Honduras',flag:flag('HN')},
  {code:'HK',dial:'+852',name:'Hong Kong',flag:flag('HK')},
  {code:'HU',dial:'+36',name:'Hungary',flag:flag('HU')},
  {code:'IS',dial:'+354',name:'Iceland',flag:flag('IS')},
  {code:'IN',dial:'+91',name:'India',flag:flag('IN')},
  {code:'ID',dial:'+62',name:'Indonesia',flag:flag('ID')},
  {code:'IR',dial:'+98',name:'Iran',flag:flag('IR')},
  {code:'IQ',dial:'+964',name:'Iraq',flag:flag('IQ')},
  {code:'IE',dial:'+353',name:'Ireland',flag:flag('IE')},
  {code:'IM',dial:'+44',name:'Isle of Man',flag:flag('IM')},
  {code:'IL',dial:'+972',name:'Israel',flag:flag('IL')},
  {code:'IT',dial:'+39',name:'Italy',flag:flag('IT')},
  {code:'JM',dial:'+1876',name:'Jamaica',flag:flag('JM')},
  {code:'JP',dial:'+81',name:'Japan',flag:flag('JP')},
  {code:'JE',dial:'+44',name:'Jersey',flag:flag('JE')},
  {code:'JO',dial:'+962',name:'Jordan',flag:flag('JO')},
  {code:'KZ',dial:'+7',name:'Kazakhstan',flag:flag('KZ')},
  {code:'KE',dial:'+254',name:'Kenya',flag:flag('KE')},
  {code:'KI',dial:'+686',name:'Kiribati',flag:flag('KI')},
  {code:'XK',dial:'+383',name:'Kosovo',flag:flag('XK')},
  {code:'KW',dial:'+965',name:'Kuwait',flag:flag('KW')},
  {code:'KG',dial:'+996',name:'Kyrgyzstan',flag:flag('KG')},
  {code:'LA',dial:'+856',name:'Laos',flag:flag('LA')},
  {code:'LV',dial:'+371',name:'Latvia',flag:flag('LV')},
  {code:'LB',dial:'+961',name:'Lebanon',flag:flag('LB')},
  {code:'LS',dial:'+266',name:'Lesotho',flag:flag('LS')},
  {code:'LR',dial:'+231',name:'Liberia',flag:flag('LR')},
  {code:'LY',dial:'+218',name:'Libya',flag:flag('LY')},
  {code:'LI',dial:'+423',name:'Liechtenstein',flag:flag('LI')},
  {code:'LT',dial:'+370',name:'Lithuania',flag:flag('LT')},
  {code:'LU',dial:'+352',name:'Luxembourg',flag:flag('LU')},
  {code:'MO',dial:'+853',name:'Macau',flag:flag('MO')},
  {code:'MG',dial:'+261',name:'Madagascar',flag:flag('MG')},
  {code:'MW',dial:'+265',name:'Malawi',flag:flag('MW')},
  {code:'MY',dial:'+60',name:'Malaysia',flag:flag('MY')},
  {code:'MV',dial:'+960',name:'Maldives',flag:flag('MV')},
  {code:'ML',dial:'+223',name:'Mali',flag:flag('ML')},
  {code:'MT',dial:'+356',name:'Malta',flag:flag('MT')},
  {code:'MH',dial:'+692',name:'Marshall Islands',flag:flag('MH')},
  {code:'MQ',dial:'+596',name:'Martinique',flag:flag('MQ')},
  {code:'MR',dial:'+222',name:'Mauritania',flag:flag('MR')},
  {code:'MU',dial:'+230',name:'Mauritius',flag:flag('MU')},
  {code:'YT',dial:'+262',name:'Mayotte',flag:flag('YT')},
  {code:'MX',dial:'+52',name:'Mexico',flag:flag('MX')},
  {code:'FM',dial:'+691',name:'Micronesia',flag:flag('FM')},
  {code:'MD',dial:'+373',name:'Moldova',flag:flag('MD')},
  {code:'MC',dial:'+377',name:'Monaco',flag:flag('MC')},
  {code:'MN',dial:'+976',name:'Mongolia',flag:flag('MN')},
  {code:'ME',dial:'+382',name:'Montenegro',flag:flag('ME')},
  {code:'MS',dial:'+1664',name:'Montserrat',flag:flag('MS')},
  {code:'MA',dial:'+212',name:'Morocco',flag:flag('MA')},
  {code:'MZ',dial:'+258',name:'Mozambique',flag:flag('MZ')},
  {code:'MM',dial:'+95',name:'Myanmar',flag:flag('MM')},
  {code:'NA',dial:'+264',name:'Namibia',flag:flag('NA')},
  {code:'NR',dial:'+674',name:'Nauru',flag:flag('NR')},
  {code:'NP',dial:'+977',name:'Nepal',flag:flag('NP')},
  {code:'NL',dial:'+31',name:'Netherlands',flag:flag('NL')},
  {code:'NC',dial:'+687',name:'New Caledonia',flag:flag('NC')},
  {code:'NZ',dial:'+64',name:'New Zealand',flag:flag('NZ')},
  {code:'NI',dial:'+505',name:'Nicaragua',flag:flag('NI')},
  {code:'NE',dial:'+227',name:'Niger',flag:flag('NE')},
  {code:'NG',dial:'+234',name:'Nigeria',flag:flag('NG')},
  {code:'NU',dial:'+683',name:'Niue',flag:flag('NU')},
  {code:'NF',dial:'+672',name:'Norfolk Island',flag:flag('NF')},
  {code:'KP',dial:'+850',name:'North Korea',flag:flag('KP')},
  {code:'MK',dial:'+389',name:'North Macedonia',flag:flag('MK')},
  {code:'MP',dial:'+1670',name:'Northern Mariana Islands',flag:flag('MP')},
  {code:'NO',dial:'+47',name:'Norway',flag:flag('NO')},
  {code:'OM',dial:'+968',name:'Oman',flag:flag('OM')},
  {code:'PK',dial:'+92',name:'Pakistan',flag:flag('PK')},
  {code:'PW',dial:'+680',name:'Palau',flag:flag('PW')},
  {code:'PS',dial:'+970',name:'Palestine',flag:flag('PS')},
  {code:'PA',dial:'+507',name:'Panama',flag:flag('PA')},
  {code:'PG',dial:'+675',name:'Papua New Guinea',flag:flag('PG')},
  {code:'PY',dial:'+595',name:'Paraguay',flag:flag('PY')},
  {code:'PE',dial:'+51',name:'Peru',flag:flag('PE')},
  {code:'PH',dial:'+63',name:'Philippines',flag:flag('PH')},
  {code:'PN',dial:'+64',name:'Pitcairn Islands',flag:flag('PN')},
  {code:'PL',dial:'+48',name:'Poland',flag:flag('PL')},
  {code:'PT',dial:'+351',name:'Portugal',flag:flag('PT')},
  {code:'PR',dial:'+1',name:'Puerto Rico',flag:flag('PR')},
  {code:'QA',dial:'+974',name:'Qatar',flag:flag('QA')},
  {code:'RE',dial:'+262',name:'Réunion',flag:flag('RE')},
  {code:'RO',dial:'+40',name:'Romania',flag:flag('RO')},
  {code:'RU',dial:'+7',name:'Russia',flag:flag('RU')},
  {code:'RW',dial:'+250',name:'Rwanda',flag:flag('RW')},
  {code:'BL',dial:'+590',name:'Saint Barthélemy',flag:flag('BL')},
  {code:'SH',dial:'+290',name:'Saint Helena, Ascension and Tristan da Cunha',flag:flag('SH')},
  {code:'KN',dial:'+1869',name:'Saint Kitts and Nevis',flag:flag('KN')},
  {code:'LC',dial:'+1758',name:'Saint Lucia',flag:flag('LC')},
  {code:'MF',dial:'+590',name:'Saint Martin',flag:flag('MF')},
  {code:'PM',dial:'+508',name:'Saint Pierre and Miquelon',flag:flag('PM')},
  {code:'VC',dial:'+1784',name:'Saint Vincent and the Grenadines',flag:flag('VC')},
  {code:'WS',dial:'+685',name:'Samoa',flag:flag('WS')},
  {code:'SM',dial:'+378',name:'San Marino',flag:flag('SM')},
  {code:'ST',dial:'+239',name:'Sao Tome and Principe',flag:flag('ST')},
  {code:'SA',dial:'+966',name:'Saudi Arabia',flag:flag('SA')},
  {code:'SN',dial:'+221',name:'Senegal',flag:flag('SN')},
  {code:'RS',dial:'+381',name:'Serbia',flag:flag('RS')},
  {code:'SC',dial:'+248',name:'Seychelles',flag:flag('SC')},
  {code:'SL',dial:'+232',name:'Sierra Leone',flag:flag('SL')},
  {code:'SG',dial:'+65',name:'Singapore',flag:flag('SG')},
  {code:'SX',dial:'+1721',name:'Sint Maarten',flag:flag('SX')},
  {code:'SK',dial:'+421',name:'Slovakia',flag:flag('SK')},
  {code:'SI',dial:'+386',name:'Slovenia',flag:flag('SI')},
  {code:'SB',dial:'+677',name:'Solomon Islands',flag:flag('SB')},
  {code:'SO',dial:'+252',name:'Somalia',flag:flag('SO')},
  {code:'ZA',dial:'+27',name:'South Africa',flag:flag('ZA')},
  {code:'GS',dial:'+500',name:'South Georgia',flag:flag('GS')},
  {code:'KR',dial:'+82',name:'South Korea',flag:flag('KR')},
  {code:'SS',dial:'+211',name:'South Sudan',flag:flag('SS')},
  {code:'ES',dial:'+34',name:'Spain',flag:flag('ES')},
  {code:'LK',dial:'+94',name:'Sri Lanka',flag:flag('LK')},
  {code:'SD',dial:'+249',name:'Sudan',flag:flag('SD')},
  {code:'SR',dial:'+597',name:'Suriname',flag:flag('SR')},
  {code:'SJ',dial:'+47',name:'Svalbard and Jan Mayen',flag:flag('SJ')},
  {code:'SE',dial:'+46',name:'Sweden',flag:flag('SE')},
  {code:'CH',dial:'+41',name:'Switzerland',flag:flag('CH')},
  {code:'SY',dial:'+963',name:'Syria',flag:flag('SY')},
  {code:'TW',dial:'+886',name:'Taiwan',flag:flag('TW')},
  {code:'TJ',dial:'+992',name:'Tajikistan',flag:flag('TJ')},
  {code:'TZ',dial:'+255',name:'Tanzania',flag:flag('TZ')},
  {code:'TH',dial:'+66',name:'Thailand',flag:flag('TH')},
  {code:'TL',dial:'+670',name:'Timor-Leste',flag:flag('TL')},
  {code:'TG',dial:'+228',name:'Togo',flag:flag('TG')},
  {code:'TK',dial:'+690',name:'Tokelau',flag:flag('TK')},
  {code:'TO',dial:'+676',name:'Tonga',flag:flag('TO')},
  {code:'TT',dial:'+1868',name:'Trinidad and Tobago',flag:flag('TT')},
  {code:'TN',dial:'+216',name:'Tunisia',flag:flag('TN')},
  {code:'TR',dial:'+90',name:'Türkiye',flag:flag('TR')},
  {code:'TM',dial:'+993',name:'Turkmenistan',flag:flag('TM')},
  {code:'TC',dial:'+1649',name:'Turks and Caicos Islands',flag:flag('TC')},
  {code:'TV',dial:'+688',name:'Tuvalu',flag:flag('TV')},
  {code:'UG',dial:'+256',name:'Uganda',flag:flag('UG')},
  {code:'UA',dial:'+380',name:'Ukraine',flag:flag('UA')},
  {code:'AE',dial:'+971',name:'United Arab Emirates',flag:flag('AE')},
  {code:'GB',dial:'+44',name:'United Kingdom',flag:flag('GB')},
  {code:'US',dial:'+1',name:'United States',flag:flag('US')},
  {code:'UM',dial:'+1',name:'United States Minor Outlying Islands',flag:flag('UM')},
  {code:'VI',dial:'+1340',name:'United States Virgin Islands',flag:flag('VI')},
  {code:'UY',dial:'+598',name:'Uruguay',flag:flag('UY')},
  {code:'UZ',dial:'+998',name:'Uzbekistan',flag:flag('UZ')},
  {code:'VU',dial:'+678',name:'Vanuatu',flag:flag('VU')},
  {code:'VA',dial:'+39',name:'Vatican City',flag:flag('VA')},
  {code:'VE',dial:'+58',name:'Venezuela',flag:flag('VE')},
  {code:'VN',dial:'+84',name:'Vietnam',flag:flag('VN')},
  {code:'WF',dial:'+681',name:'Wallis and Futuna',flag:flag('WF')},
  {code:'EH',dial:'+212',name:'Western Sahara',flag:flag('EH')},
  {code:'YE',dial:'+967',name:'Yemen',flag:flag('YE')},
  {code:'ZM',dial:'+260',name:'Zambia',flag:flag('ZM')},
  {code:'ZW',dial:'+263',name:'Zimbabwe',flag:flag('ZW')},
];
