// Auto-generated ISO 3166-1 country list for passport entries — run: node scripts/gen-countries.js
export interface IsoCountry {
  alpha2: string;
  alpha3: string;
  name: string;
  flag: string;
  searchAliases?: string[];
}

function flag(cca2: string): string {
  return cca2
    .toUpperCase()
    .split('')
    .map(c => String.fromCodePoint(0x1f1e6 - 65 + c.charCodeAt(0)))
    .join('');
}

export const ISO_COUNTRIES: IsoCountry[] = [
  {alpha2:'AF',alpha3:'AFG',name:'Afghanistan',flag:flag('AF')},
  {alpha2:'AX',alpha3:'ALA',name:'Åland Islands',flag:flag('AX')},
  {alpha2:'AL',alpha3:'ALB',name:'Albania',flag:flag('AL')},
  {alpha2:'DZ',alpha3:'DZA',name:'Algeria',flag:flag('DZ')},
  {alpha2:'AS',alpha3:'ASM',name:'American Samoa',flag:flag('AS')},
  {alpha2:'AD',alpha3:'AND',name:'Andorra',flag:flag('AD')},
  {alpha2:'AO',alpha3:'AGO',name:'Angola',flag:flag('AO')},
  {alpha2:'AI',alpha3:'AIA',name:'Anguilla',flag:flag('AI')},
  {alpha2:'AQ',alpha3:'ATA',name:'Antarctica',flag:flag('AQ')},
  {alpha2:'AG',alpha3:'ATG',name:'Antigua and Barbuda',flag:flag('AG')},
  {alpha2:'AR',alpha3:'ARG',name:'Argentina',flag:flag('AR')},
  {alpha2:'AM',alpha3:'ARM',name:'Armenia',flag:flag('AM')},
  {alpha2:'AW',alpha3:'ABW',name:'Aruba',flag:flag('AW')},
  {alpha2:'AU',alpha3:'AUS',name:'Australia',flag:flag('AU')},
  {alpha2:'AT',alpha3:'AUT',name:'Austria',flag:flag('AT')},
  {alpha2:'AZ',alpha3:'AZE',name:'Azerbaijan',flag:flag('AZ')},
  {alpha2:'BS',alpha3:'BHS',name:'Bahamas',flag:flag('BS')},
  {alpha2:'BH',alpha3:'BHR',name:'Bahrain',flag:flag('BH')},
  {alpha2:'BD',alpha3:'BGD',name:'Bangladesh',flag:flag('BD')},
  {alpha2:'BB',alpha3:'BRB',name:'Barbados',flag:flag('BB')},
  {alpha2:'BY',alpha3:'BLR',name:'Belarus',flag:flag('BY')},
  {alpha2:'BE',alpha3:'BEL',name:'Belgium',flag:flag('BE')},
  {alpha2:'BZ',alpha3:'BLZ',name:'Belize',flag:flag('BZ')},
  {alpha2:'BJ',alpha3:'BEN',name:'Benin',flag:flag('BJ')},
  {alpha2:'BM',alpha3:'BMU',name:'Bermuda',flag:flag('BM')},
  {alpha2:'BT',alpha3:'BTN',name:'Bhutan',flag:flag('BT')},
  {alpha2:'BO',alpha3:'BOL',name:'Bolivia',flag:flag('BO')},
  {alpha2:'BA',alpha3:'BIH',name:'Bosnia and Herzegovina',flag:flag('BA')},
  {alpha2:'BW',alpha3:'BWA',name:'Botswana',flag:flag('BW')},
  {alpha2:'BV',alpha3:'BVT',name:'Bouvet Island',flag:flag('BV')},
  {alpha2:'BR',alpha3:'BRA',name:'Brazil',flag:flag('BR')},
  {alpha2:'IO',alpha3:'IOT',name:'British Indian Ocean Territory',flag:flag('IO')},
  {alpha2:'VG',alpha3:'VGB',name:'British Virgin Islands',flag:flag('VG')},
  {alpha2:'BN',alpha3:'BRN',name:'Brunei',flag:flag('BN')},
  {alpha2:'BG',alpha3:'BGR',name:'Bulgaria',flag:flag('BG')},
  {alpha2:'BF',alpha3:'BFA',name:'Burkina Faso',flag:flag('BF')},
  {alpha2:'BI',alpha3:'BDI',name:'Burundi',flag:flag('BI')},
  {alpha2:'KH',alpha3:'KHM',name:'Cambodia',flag:flag('KH')},
  {alpha2:'CM',alpha3:'CMR',name:'Cameroon',flag:flag('CM')},
  {alpha2:'CA',alpha3:'CAN',name:'Canada',flag:flag('CA')},
  {alpha2:'CV',alpha3:'CPV',name:'Cape Verde',flag:flag('CV')},
  {alpha2:'BQ',alpha3:'BES',name:'Caribbean Netherlands',flag:flag('BQ')},
  {alpha2:'KY',alpha3:'CYM',name:'Cayman Islands',flag:flag('KY')},
  {alpha2:'CF',alpha3:'CAF',name:'Central African Republic',flag:flag('CF')},
  {alpha2:'TD',alpha3:'TCD',name:'Chad',flag:flag('TD')},
  {alpha2:'CL',alpha3:'CHL',name:'Chile',flag:flag('CL')},
  {alpha2:'CN',alpha3:'CHN',name:'China',flag:flag('CN')},
  {alpha2:'CX',alpha3:'CXR',name:'Christmas Island',flag:flag('CX')},
  {alpha2:'CC',alpha3:'CCK',name:'Cocos (Keeling) Islands',flag:flag('CC')},
  {alpha2:'CO',alpha3:'COL',name:'Colombia',flag:flag('CO')},
  {alpha2:'KM',alpha3:'COM',name:'Comoros',flag:flag('KM')},
  {alpha2:'CG',alpha3:'COG',name:'Congo',flag:flag('CG'),searchAliases:['republic of the congo']},
  {alpha2:'CK',alpha3:'COK',name:'Cook Islands',flag:flag('CK')},
  {alpha2:'CR',alpha3:'CRI',name:'Costa Rica',flag:flag('CR')},
  {alpha2:'CI',alpha3:'CIV',name:'Côte d\'Ivoire',flag:flag('CI')},
  {alpha2:'HR',alpha3:'HRV',name:'Croatia',flag:flag('HR')},
  {alpha2:'CU',alpha3:'CUB',name:'Cuba',flag:flag('CU')},
  {alpha2:'CW',alpha3:'CUW',name:'Curaçao',flag:flag('CW')},
  {alpha2:'CY',alpha3:'CYP',name:'Cyprus',flag:flag('CY')},
  {alpha2:'CZ',alpha3:'CZE',name:'Czechia',flag:flag('CZ'),searchAliases:['czech republic','czechia']},
  {alpha2:'DK',alpha3:'DNK',name:'Denmark',flag:flag('DK')},
  {alpha2:'DJ',alpha3:'DJI',name:'Djibouti',flag:flag('DJ')},
  {alpha2:'DM',alpha3:'DMA',name:'Dominica',flag:flag('DM')},
  {alpha2:'DO',alpha3:'DOM',name:'Dominican Republic',flag:flag('DO')},
  {alpha2:'CD',alpha3:'COD',name:'DR Congo',flag:flag('CD'),searchAliases:['drc','democratic republic of the congo','dr congo']},
  {alpha2:'EC',alpha3:'ECU',name:'Ecuador',flag:flag('EC')},
  {alpha2:'EG',alpha3:'EGY',name:'Egypt',flag:flag('EG')},
  {alpha2:'SV',alpha3:'SLV',name:'El Salvador',flag:flag('SV')},
  {alpha2:'GQ',alpha3:'GNQ',name:'Equatorial Guinea',flag:flag('GQ')},
  {alpha2:'ER',alpha3:'ERI',name:'Eritrea',flag:flag('ER')},
  {alpha2:'EE',alpha3:'EST',name:'Estonia',flag:flag('EE')},
  {alpha2:'SZ',alpha3:'SWZ',name:'Eswatini',flag:flag('SZ'),searchAliases:['swaziland']},
  {alpha2:'ET',alpha3:'ETH',name:'Ethiopia',flag:flag('ET')},
  {alpha2:'FK',alpha3:'FLK',name:'Falkland Islands',flag:flag('FK')},
  {alpha2:'FO',alpha3:'FRO',name:'Faroe Islands',flag:flag('FO')},
  {alpha2:'FJ',alpha3:'FJI',name:'Fiji',flag:flag('FJ')},
  {alpha2:'FI',alpha3:'FIN',name:'Finland',flag:flag('FI')},
  {alpha2:'FR',alpha3:'FRA',name:'France',flag:flag('FR')},
  {alpha2:'GF',alpha3:'GUF',name:'French Guiana',flag:flag('GF')},
  {alpha2:'PF',alpha3:'PYF',name:'French Polynesia',flag:flag('PF')},
  {alpha2:'TF',alpha3:'ATF',name:'French Southern and Antarctic Lands',flag:flag('TF')},
  {alpha2:'GA',alpha3:'GAB',name:'Gabon',flag:flag('GA')},
  {alpha2:'GM',alpha3:'GMB',name:'Gambia',flag:flag('GM')},
  {alpha2:'GE',alpha3:'GEO',name:'Georgia',flag:flag('GE')},
  {alpha2:'DE',alpha3:'DEU',name:'Germany',flag:flag('DE')},
  {alpha2:'GH',alpha3:'GHA',name:'Ghana',flag:flag('GH')},
  {alpha2:'GI',alpha3:'GIB',name:'Gibraltar',flag:flag('GI')},
  {alpha2:'GR',alpha3:'GRC',name:'Greece',flag:flag('GR')},
  {alpha2:'GL',alpha3:'GRL',name:'Greenland',flag:flag('GL')},
  {alpha2:'GD',alpha3:'GRD',name:'Grenada',flag:flag('GD')},
  {alpha2:'GP',alpha3:'GLP',name:'Guadeloupe',flag:flag('GP')},
  {alpha2:'GU',alpha3:'GUM',name:'Guam',flag:flag('GU')},
  {alpha2:'GT',alpha3:'GTM',name:'Guatemala',flag:flag('GT')},
  {alpha2:'GG',alpha3:'GGY',name:'Guernsey',flag:flag('GG')},
  {alpha2:'GN',alpha3:'GIN',name:'Guinea',flag:flag('GN')},
  {alpha2:'GW',alpha3:'GNB',name:'Guinea-Bissau',flag:flag('GW')},
  {alpha2:'GY',alpha3:'GUY',name:'Guyana',flag:flag('GY')},
  {alpha2:'HT',alpha3:'HTI',name:'Haiti',flag:flag('HT')},
  {alpha2:'HM',alpha3:'HMD',name:'Heard Island and McDonald Islands',flag:flag('HM')},
  {alpha2:'HN',alpha3:'HND',name:'Honduras',flag:flag('HN')},
  {alpha2:'HK',alpha3:'HKG',name:'Hong Kong',flag:flag('HK')},
  {alpha2:'HU',alpha3:'HUN',name:'Hungary',flag:flag('HU')},
  {alpha2:'IS',alpha3:'ISL',name:'Iceland',flag:flag('IS')},
  {alpha2:'IN',alpha3:'IND',name:'India',flag:flag('IN')},
  {alpha2:'ID',alpha3:'IDN',name:'Indonesia',flag:flag('ID')},
  {alpha2:'IR',alpha3:'IRN',name:'Iran',flag:flag('IR')},
  {alpha2:'IQ',alpha3:'IRQ',name:'Iraq',flag:flag('IQ')},
  {alpha2:'IE',alpha3:'IRL',name:'Ireland',flag:flag('IE')},
  {alpha2:'IM',alpha3:'IMN',name:'Isle of Man',flag:flag('IM')},
  {alpha2:'IL',alpha3:'ISR',name:'Israel',flag:flag('IL')},
  {alpha2:'IT',alpha3:'ITA',name:'Italy',flag:flag('IT')},
  {alpha2:'JM',alpha3:'JAM',name:'Jamaica',flag:flag('JM')},
  {alpha2:'JP',alpha3:'JPN',name:'Japan',flag:flag('JP')},
  {alpha2:'JE',alpha3:'JEY',name:'Jersey',flag:flag('JE')},
  {alpha2:'JO',alpha3:'JOR',name:'Jordan',flag:flag('JO')},
  {alpha2:'KZ',alpha3:'KAZ',name:'Kazakhstan',flag:flag('KZ')},
  {alpha2:'KE',alpha3:'KEN',name:'Kenya',flag:flag('KE')},
  {alpha2:'KI',alpha3:'KIR',name:'Kiribati',flag:flag('KI')},
  {alpha2:'XK',alpha3:'UNK',name:'Kosovo',flag:flag('XK')},
  {alpha2:'KW',alpha3:'KWT',name:'Kuwait',flag:flag('KW')},
  {alpha2:'KG',alpha3:'KGZ',name:'Kyrgyzstan',flag:flag('KG')},
  {alpha2:'LA',alpha3:'LAO',name:'Laos',flag:flag('LA'),searchAliases:['laos']},
  {alpha2:'LV',alpha3:'LVA',name:'Latvia',flag:flag('LV')},
  {alpha2:'LB',alpha3:'LBN',name:'Lebanon',flag:flag('LB')},
  {alpha2:'LS',alpha3:'LSO',name:'Lesotho',flag:flag('LS')},
  {alpha2:'LR',alpha3:'LBR',name:'Liberia',flag:flag('LR')},
  {alpha2:'LY',alpha3:'LBY',name:'Libya',flag:flag('LY')},
  {alpha2:'LI',alpha3:'LIE',name:'Liechtenstein',flag:flag('LI')},
  {alpha2:'LT',alpha3:'LTU',name:'Lithuania',flag:flag('LT')},
  {alpha2:'LU',alpha3:'LUX',name:'Luxembourg',flag:flag('LU')},
  {alpha2:'MO',alpha3:'MAC',name:'Macau',flag:flag('MO')},
  {alpha2:'MG',alpha3:'MDG',name:'Madagascar',flag:flag('MG')},
  {alpha2:'MW',alpha3:'MWI',name:'Malawi',flag:flag('MW')},
  {alpha2:'MY',alpha3:'MYS',name:'Malaysia',flag:flag('MY')},
  {alpha2:'MV',alpha3:'MDV',name:'Maldives',flag:flag('MV')},
  {alpha2:'ML',alpha3:'MLI',name:'Mali',flag:flag('ML')},
  {alpha2:'MT',alpha3:'MLT',name:'Malta',flag:flag('MT')},
  {alpha2:'MH',alpha3:'MHL',name:'Marshall Islands',flag:flag('MH')},
  {alpha2:'MQ',alpha3:'MTQ',name:'Martinique',flag:flag('MQ')},
  {alpha2:'MR',alpha3:'MRT',name:'Mauritania',flag:flag('MR')},
  {alpha2:'MU',alpha3:'MUS',name:'Mauritius',flag:flag('MU')},
  {alpha2:'YT',alpha3:'MYT',name:'Mayotte',flag:flag('YT')},
  {alpha2:'MX',alpha3:'MEX',name:'Mexico',flag:flag('MX')},
  {alpha2:'FM',alpha3:'FSM',name:'Micronesia',flag:flag('FM')},
  {alpha2:'MD',alpha3:'MDA',name:'Moldova',flag:flag('MD')},
  {alpha2:'MC',alpha3:'MCO',name:'Monaco',flag:flag('MC')},
  {alpha2:'MN',alpha3:'MNG',name:'Mongolia',flag:flag('MN')},
  {alpha2:'ME',alpha3:'MNE',name:'Montenegro',flag:flag('ME')},
  {alpha2:'MS',alpha3:'MSR',name:'Montserrat',flag:flag('MS')},
  {alpha2:'MA',alpha3:'MAR',name:'Morocco',flag:flag('MA')},
  {alpha2:'MZ',alpha3:'MOZ',name:'Mozambique',flag:flag('MZ')},
  {alpha2:'MM',alpha3:'MMR',name:'Myanmar',flag:flag('MM')},
  {alpha2:'NA',alpha3:'NAM',name:'Namibia',flag:flag('NA')},
  {alpha2:'NR',alpha3:'NRU',name:'Nauru',flag:flag('NR')},
  {alpha2:'NP',alpha3:'NPL',name:'Nepal',flag:flag('NP')},
  {alpha2:'NL',alpha3:'NLD',name:'Netherlands',flag:flag('NL')},
  {alpha2:'NC',alpha3:'NCL',name:'New Caledonia',flag:flag('NC')},
  {alpha2:'NZ',alpha3:'NZL',name:'New Zealand',flag:flag('NZ')},
  {alpha2:'NI',alpha3:'NIC',name:'Nicaragua',flag:flag('NI')},
  {alpha2:'NE',alpha3:'NER',name:'Niger',flag:flag('NE')},
  {alpha2:'NG',alpha3:'NGA',name:'Nigeria',flag:flag('NG')},
  {alpha2:'NU',alpha3:'NIU',name:'Niue',flag:flag('NU')},
  {alpha2:'NF',alpha3:'NFK',name:'Norfolk Island',flag:flag('NF')},
  {alpha2:'KP',alpha3:'PRK',name:'North Korea',flag:flag('KP'),searchAliases:['dprk','north korea','democratic peoples republic of korea']},
  {alpha2:'MK',alpha3:'MKD',name:'North Macedonia',flag:flag('MK'),searchAliases:['macedonia']},
  {alpha2:'MP',alpha3:'MNP',name:'Northern Mariana Islands',flag:flag('MP')},
  {alpha2:'NO',alpha3:'NOR',name:'Norway',flag:flag('NO')},
  {alpha2:'OM',alpha3:'OMN',name:'Oman',flag:flag('OM')},
  {alpha2:'PK',alpha3:'PAK',name:'Pakistan',flag:flag('PK')},
  {alpha2:'PW',alpha3:'PLW',name:'Palau',flag:flag('PW')},
  {alpha2:'PS',alpha3:'PSE',name:'Palestine',flag:flag('PS'),searchAliases:['palestine','palestinian territories','west bank','gaza']},
  {alpha2:'PA',alpha3:'PAN',name:'Panama',flag:flag('PA')},
  {alpha2:'PG',alpha3:'PNG',name:'Papua New Guinea',flag:flag('PG')},
  {alpha2:'PY',alpha3:'PRY',name:'Paraguay',flag:flag('PY')},
  {alpha2:'PE',alpha3:'PER',name:'Peru',flag:flag('PE')},
  {alpha2:'PH',alpha3:'PHL',name:'Philippines',flag:flag('PH')},
  {alpha2:'PN',alpha3:'PCN',name:'Pitcairn Islands',flag:flag('PN')},
  {alpha2:'PL',alpha3:'POL',name:'Poland',flag:flag('PL')},
  {alpha2:'PT',alpha3:'PRT',name:'Portugal',flag:flag('PT')},
  {alpha2:'PR',alpha3:'PRI',name:'Puerto Rico',flag:flag('PR')},
  {alpha2:'QA',alpha3:'QAT',name:'Qatar',flag:flag('QA')},
  {alpha2:'RE',alpha3:'REU',name:'Réunion',flag:flag('RE')},
  {alpha2:'RO',alpha3:'ROU',name:'Romania',flag:flag('RO')},
  {alpha2:'RU',alpha3:'RUS',name:'Russia',flag:flag('RU')},
  {alpha2:'RW',alpha3:'RWA',name:'Rwanda',flag:flag('RW')},
  {alpha2:'BL',alpha3:'BLM',name:'Saint Barthélemy',flag:flag('BL')},
  {alpha2:'SH',alpha3:'SHN',name:'Saint Helena, Ascension and Tristan da Cunha',flag:flag('SH')},
  {alpha2:'KN',alpha3:'KNA',name:'Saint Kitts and Nevis',flag:flag('KN')},
  {alpha2:'LC',alpha3:'LCA',name:'Saint Lucia',flag:flag('LC')},
  {alpha2:'MF',alpha3:'MAF',name:'Saint Martin',flag:flag('MF')},
  {alpha2:'PM',alpha3:'SPM',name:'Saint Pierre and Miquelon',flag:flag('PM')},
  {alpha2:'VC',alpha3:'VCT',name:'Saint Vincent and the Grenadines',flag:flag('VC')},
  {alpha2:'WS',alpha3:'WSM',name:'Samoa',flag:flag('WS')},
  {alpha2:'SM',alpha3:'SMR',name:'San Marino',flag:flag('SM')},
  {alpha2:'ST',alpha3:'STP',name:'Sao Tome and Principe',flag:flag('ST'),searchAliases:['sao tome','sao tome and principe','stp','são tomé','são tomé and príncipe']},
  {alpha2:'SA',alpha3:'SAU',name:'Saudi Arabia',flag:flag('SA')},
  {alpha2:'SN',alpha3:'SEN',name:'Senegal',flag:flag('SN')},
  {alpha2:'RS',alpha3:'SRB',name:'Serbia',flag:flag('RS')},
  {alpha2:'SC',alpha3:'SYC',name:'Seychelles',flag:flag('SC')},
  {alpha2:'SL',alpha3:'SLE',name:'Sierra Leone',flag:flag('SL')},
  {alpha2:'SG',alpha3:'SGP',name:'Singapore',flag:flag('SG')},
  {alpha2:'SX',alpha3:'SXM',name:'Sint Maarten',flag:flag('SX')},
  {alpha2:'SK',alpha3:'SVK',name:'Slovakia',flag:flag('SK')},
  {alpha2:'SI',alpha3:'SVN',name:'Slovenia',flag:flag('SI')},
  {alpha2:'SB',alpha3:'SLB',name:'Solomon Islands',flag:flag('SB')},
  {alpha2:'SO',alpha3:'SOM',name:'Somalia',flag:flag('SO')},
  {alpha2:'ZA',alpha3:'ZAF',name:'South Africa',flag:flag('ZA')},
  {alpha2:'GS',alpha3:'SGS',name:'South Georgia',flag:flag('GS')},
  {alpha2:'KR',alpha3:'KOR',name:'South Korea',flag:flag('KR'),searchAliases:['rok','south korea','republic of korea']},
  {alpha2:'SS',alpha3:'SSD',name:'South Sudan',flag:flag('SS')},
  {alpha2:'ES',alpha3:'ESP',name:'Spain',flag:flag('ES')},
  {alpha2:'LK',alpha3:'LKA',name:'Sri Lanka',flag:flag('LK')},
  {alpha2:'SD',alpha3:'SDN',name:'Sudan',flag:flag('SD')},
  {alpha2:'SR',alpha3:'SUR',name:'Suriname',flag:flag('SR')},
  {alpha2:'SJ',alpha3:'SJM',name:'Svalbard and Jan Mayen',flag:flag('SJ')},
  {alpha2:'SE',alpha3:'SWE',name:'Sweden',flag:flag('SE')},
  {alpha2:'CH',alpha3:'CHE',name:'Switzerland',flag:flag('CH')},
  {alpha2:'SY',alpha3:'SYR',name:'Syria',flag:flag('SY')},
  {alpha2:'TW',alpha3:'TWN',name:'Taiwan',flag:flag('TW')},
  {alpha2:'TJ',alpha3:'TJK',name:'Tajikistan',flag:flag('TJ')},
  {alpha2:'TZ',alpha3:'TZA',name:'Tanzania',flag:flag('TZ')},
  {alpha2:'TH',alpha3:'THA',name:'Thailand',flag:flag('TH')},
  {alpha2:'TL',alpha3:'TLS',name:'Timor-Leste',flag:flag('TL'),searchAliases:['east timor','timor leste']},
  {alpha2:'TG',alpha3:'TGO',name:'Togo',flag:flag('TG')},
  {alpha2:'TK',alpha3:'TKL',name:'Tokelau',flag:flag('TK')},
  {alpha2:'TO',alpha3:'TON',name:'Tonga',flag:flag('TO')},
  {alpha2:'TT',alpha3:'TTO',name:'Trinidad and Tobago',flag:flag('TT')},
  {alpha2:'TN',alpha3:'TUN',name:'Tunisia',flag:flag('TN')},
  {alpha2:'TR',alpha3:'TUR',name:'Türkiye',flag:flag('TR')},
  {alpha2:'TM',alpha3:'TKM',name:'Turkmenistan',flag:flag('TM')},
  {alpha2:'TC',alpha3:'TCA',name:'Turks and Caicos Islands',flag:flag('TC')},
  {alpha2:'TV',alpha3:'TUV',name:'Tuvalu',flag:flag('TV')},
  {alpha2:'UG',alpha3:'UGA',name:'Uganda',flag:flag('UG')},
  {alpha2:'UA',alpha3:'UKR',name:'Ukraine',flag:flag('UA')},
  {alpha2:'AE',alpha3:'ARE',name:'United Arab Emirates',flag:flag('AE'),searchAliases:['uae','emirates']},
  {alpha2:'GB',alpha3:'GBR',name:'United Kingdom',flag:flag('GB'),searchAliases:['england','scotland','wales','northern ireland','britain','great britain','uk']},
  {alpha2:'US',alpha3:'USA',name:'United States',flag:flag('US'),searchAliases:['usa','america','united states of america']},
  {alpha2:'UM',alpha3:'UMI',name:'United States Minor Outlying Islands',flag:flag('UM')},
  {alpha2:'VI',alpha3:'VIR',name:'United States Virgin Islands',flag:flag('VI')},
  {alpha2:'UY',alpha3:'URY',name:'Uruguay',flag:flag('UY')},
  {alpha2:'UZ',alpha3:'UZB',name:'Uzbekistan',flag:flag('UZ')},
  {alpha2:'VU',alpha3:'VUT',name:'Vanuatu',flag:flag('VU')},
  {alpha2:'VA',alpha3:'VAT',name:'Vatican City',flag:flag('VA')},
  {alpha2:'VE',alpha3:'VEN',name:'Venezuela',flag:flag('VE')},
  {alpha2:'VN',alpha3:'VNM',name:'Vietnam',flag:flag('VN')},
  {alpha2:'WF',alpha3:'WLF',name:'Wallis and Futuna',flag:flag('WF')},
  {alpha2:'EH',alpha3:'ESH',name:'Western Sahara',flag:flag('EH')},
  {alpha2:'YE',alpha3:'YEM',name:'Yemen',flag:flag('YE')},
  {alpha2:'ZM',alpha3:'ZMB',name:'Zambia',flag:flag('ZM')},
  {alpha2:'ZW',alpha3:'ZWE',name:'Zimbabwe',flag:flag('ZW')},
];

export function findIsoCountryByAlpha3(alpha3: string): IsoCountry | undefined {
  return ISO_COUNTRIES.find(c => c.alpha3 === alpha3.toUpperCase());
}

export function findIsoCountryByAlpha2(alpha2: string): IsoCountry | undefined {
  return ISO_COUNTRIES.find(c => c.alpha2 === alpha2.toUpperCase());
}

export function searchIsoCountries(query: string, limit = 30): IsoCountry[] {
  const q = query.trim().toLowerCase();
  if (!q) {
    return ISO_COUNTRIES.slice(0, limit);
  }
  return ISO_COUNTRIES.filter(
    c =>
      c.name.toLowerCase().includes(q) ||
      c.alpha3.toLowerCase().includes(q) ||
      c.alpha2.toLowerCase().includes(q) ||
      (c.searchAliases?.some(alias => alias.includes(q)) ?? false),
  ).slice(0, limit);
}
